pr:
  - main

trigger: none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        displayName: Build
        steps:
          - template: templates/build.yml
          - template: templates/push.yml

  - stage: prerelease
    dependsOn: build
    displayName: Prerelease
    jobs:
      - deployment:
        environment: Prerelease
        pool:
          vmImage: 'vs2017-win2016'
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/promote.yml
                  parameters:
                    releaseView: '0b477f7e-e363-4441-97f7-bf3189253564'
